sudo: required
services:
  - docker

before_install:
  - docker build -t soumenpatel1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run soumenpatel1/react-test npm test -- --coverage

after_success:
  - docker build -t soumenpatel1/multi-client ./client
  - docker build -t soumenpatel1/multi-nginx ./nginx
  - docker build -t soumenpatel1/multi-server ./server
  - docker build -t soumenpatel1/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push soumenpatel1/multi-client
  - docker push soumenpatel1/multi-nginx
  - docker push soumenpatel1/multi-server
  - docker push soumenpatel1/multi-workder

 